options:
  transmission_image_path:
    type: string
    default: linuxserver/transmission
    description: The docker image to install.
  transmission_image_username:
    type: string
    description: |
      The username for accessing the registry specified in transmission_image_path.
    default: ""
  transmission_image_password:
    type: string
    description: |
      The password associated with transmission_image_username for accessing the registry specified in transmission_image_path.
    default: ""
  puid:
    type: int
    description: User ID
    default: 1000
  pgid:
    type: int
    description: Group ID
    default: 1000
  user:
    type: string
    description: User
    default: transmission
  pass:
    type: string
    description: Password
    default: transmission
  timezone:
    type: string
    description: Timezone code. See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
    default: ES
  site_url:
    type: string
    description: Ingress URL to access Transmission Web UI
    default: ""
  max_file_size:
    type: int
    description: |
      The maximum file size, in megabytes.

      If there is a reverse proxy in front of Transmission, it may
      need to be configured to handle the requested size.
    default: 5
  ingress_whitelist_source_range:
    type: string
    description: |
      A comma-separated list of CIDRs to store in the ingress.kubernetes.io/whitelist-source-range annotation.

      This can be used to lock down access to Transmission based on source IP address.
    default: ""
